project_id = "suaznqybxvborpkrtdpm"

[functions.webhook-receiver]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true
