project_id = "suaznqybxvborpkrtdpm"

[functions.webhook-receiver]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.setup-totp]
verify_jwt = false

[functions.verify-totp]
verify_jwt = false

[functions.webhook-groups]
verify_jwt = false

[functions.typebot-stats]
verify_jwt = true

[functions.webhook-abandoned]
verify_jwt = false

[functions.delivery-access]
verify_jwt = false

[functions.import-transactions]
verify_jwt = true

[functions.import-abandoned-events]
verify_jwt = true
